language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

before_script:
  - python manage.py migrate

script:
  python manage.py test

env:
  - DJANGO_VERSION=1.8.13 DB_ENGINE="django.db.backends.mysql" DB_NAME="test_project" DB_USER="travis"
  - DJANGO_VERSION=1.9.5 DB_ENGINE="django.db.backends.mysql" DB_NAME="test_project" DB_USER="travis"
