language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

services:
  - mysql

before_script:
  - mysql -e 'create database jellyblog_travis;'
  - python manage.py migrate

script:
  - python manage.py test functional_test
  - python manage.py test jellyblog

env:
  global:
     - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO_VERSION=1.8.12 DB=mysql
    - DJANGO_VERSION=1.9.5 DB=mysql
