language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_script:
  - mysql -e 'create database jellyblog_travis'
  - python manage.py migrate

script:
  python manage.py test

env:
  global:
     - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO_VERSION=1.8.12 DB=mysql
    - DJANGO_VERSION=1.9.5 DB=mysql
