language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

before_script:
  - mysql -e 'create database travis_ci_db'
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  - python manage.py migrate

script:
  python manage.py test

env:
  global:
     - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO_VERSION=1.8.12 DB=mysql
    - DJANGO_VERSION=1.9.5 DB=mysql
