language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

before_script:
  - mysql -e 'create database travis_ci_db'
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - python manage.py migrate

script:
  python manage.py test

env:
  global:
     - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO_VERSION=1.8.12 DB=mysql
    - DJANGO_VERSION=1.9.5 DB=mysql
