language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - tar -xzvf geckodriver-v0.11.1-linux64.tar.gz
  - PATH=$PATH:/home/travis/build/kyunooh/JellyBlog

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - wget
  firefox: "48.0.1"
  

before_script:
  - mysql -u root -e 'create database jellyblog_travis;'
  - python manage.py makemigrations 
  - python manage.py migrate -v 3
  - python manage.py collectstatic --noinput

script:
  - python manage.py test functional_test -v 3
  - python manage.py test lifeblog -v 3
  - python manage.py test jellyblog -v 3
  - python manage.py test static_post -v 3

env:
  global:
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO_VERSION=1.8.12 DB=mysql
    - DJANGO_VERSION=1.9.4 DB=mysql
    - DJANGO_VERSION=1.9.5 DB=mysql
