# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='overlay_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
