# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellyblog', '0002_auto_20160213_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(),
        ),
    ]
