# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellyblog', '0005_auto_20161014_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='linebreaks',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
