# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('meta_tag', models.CharField(max_length=150)),
                ('view_count', models.IntegerField(default=0, editable=False)),
                ('public_doc', models.BooleanField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
